### ISSUE TITLE
Astro 4 support

### ISSUE THREAD

**Issue by olach** [sanity-io/sanity-astro#122]
This integration is not compatible with Astro 4 that was released today. When installing/updating the package the following error is shown:

```
npm install @sanity/astro
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While hidden@0.0.1
npm ERR! Found: astro@4.0.1
npm ERR! node_modules/astro
npm ERR!   astro@"^4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^2.0.0 || ^3.0.0" from @sanity/astro@2.1.4
npm ERR! node_modules/@sanity/astro
npm ERR!   @sanity/astro@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It looks that this package is locked to Astro v2 and v3. I think Astro 4 also has some breaking changes for plugin authors. For example they are now using Vite 5.

Their upgrade guide:
https://docs.astro.build/en/guides/upgrade-to/v4/

**Comment by frankstallone** [comment]
Posted a similar issue to another dependecy earlier today. It's probably simply updating the `peerDependency` of Astro to include v4.

**Comment by rasimack** [comment]
I have just created a new a new Astro 4.0 project and I am having the same issue with Sanity integration.

**Comment by narration-sd** [comment]
If the problem is, as often it can be, only the dependency presets needing to be updated, you can work around this by doing npm install with an additional flag:

`npm install [any other arguments] --legacy-peer-deps`

There are several ways, I think, but it's one apparently many use, and has worked well often enough here...

**Comment by frankstallone** [comment]
> If the problem is, as often it can be, only the dependency presets needing to be updated, you can work around this by doing npm install with an additional flag:
> 
> 
> 
> `npm install [any other arguments] --legacy-peer-deps`
> 
> 
> 
> There are several ways, I think, but it's one apparently many use, and has worked well often enough here...

This may work, but it's a terrible recommendation. A band aid, not a solution.

**Comment by narration-sd** [comment]
> This may work, but it's a terrible recommendation. A band aid, not a solution

Well, surely not a solution, you are running a risk to be sure, but rather practical when it does work,as packages are just delayed in testing, etc., to see they will get along, and there's something non-critical worth the try to see about?

**Comment by olach** [comment]
@kmelve Are you aware that this integration is not yet updated for Astro 4? This is your official Sanity integration after all, and is broken for all new Sanity users/customers.

**Comment by anouar052** [comment]
Please add support to Astro 4, you can get around in dev with --legacy-peer-deps, but it crashes when deploying to prod.
Thank you

**Comment by narration-sd** [comment]
@anouar052 , indeed Frank was correct here, --legacy-peer-deps can't do the job for this case.

However, I tried an apprach which appears to work, which is nearly as simple - just takes a few steps. What it is doing is taking away the need to compile the sanity-astor package itself, since the old one as compiled seems to get along with Astro 4, at least in a reasonably complex scene I've tried it with.

You can [find the explanation here](https://sanity-io-land.slack.com/archives/C04B7GG8YNQ/p1702420833003909?thread_ts=1701901739.752099&cid=C04B7GG8YNQ); I've just made it a little clearer with an edit this morning, that we're doing this with Astro 4.

**Comment by doesnotexist** [comment]
@narration-sd that slack link is to a private slack.  Can you please share the explanation here on github?

**Comment by narration-sd** [comment]
Hello Omar -- that should be the open Sanity slack, not private; aren't you logged into that, if you work with Sanity?  Or something's gone wrong...  I did just try it, went to the right place, but all things can happen :)

Here's what I wrote. It ought to be simpler to do, but you have to be sure to get all the things clean for turbo, etc.:

@Ola Christensson et al, first, apologies to Knut on prior message; as you were actually addressing him, when I looked more closely.

I've tried something that might take the pressure off, let you use Astro 4 without a sanity-astro upgrade just yet. As that's not compatible in the way we see actually having to do with Vite, with Astro 4 upgrades on its package.json dependencies.

However, the package itself prepared for Astro 3 does appear compatible with Astro 4, at least enough to run a fairly complex project here. These steps will let you do that, and relieve Knut for what we can all surely appreciate is likely a bit of time needed to get the Vite issue sorted out.

- the simplest way to get the sanity-astro source out of play, given this is a turbo monorepo which would try to build it, is simply to remove it. If you want to operate on a local version of the package once that's upgraded, you can simply clone later in another folder, and copy it back in. So, delete the /packages/sanity-astro folder, from your project.

- Now, we need to add the package in the normal way, from npm., replacing the "*" version whichuses the local.  So, in any /apps folders you have, /apps/example in the original, do an npm i @sanity/astro. 

- That step will also have installed the actual @sanity/astro in the top-level node_modules, not locally, due to the workspace-turborepo arrangements.

- Now, if you've done an npm i in each of your packages and apps folders, after you've upgraded  to Astro 4 (or checked the upgrade for currency), using npx @astrojs/upgrade in each, you're ready to build. 

- You need to build any local packages to be ready even if you're using npm run dev on an app, so the easiest way to do this, and also assure each app is ready, is to go to the top folder of the prroject, and issue npm run build. This will operate turbo, and it will automatically build each folder according to dependencies, which means any packages first.

At this point, you should be ready to go. In a chosen apps folder, use your npm run dev, and things should go normally. I'm doing this using a number of packages, including Netlify ability, and with the embedded Studio editing fine for it. If not, then Knut's upgrade will be along soon.

**Comment by doesnotexist** [comment]
My workaround is that I made a temporary fork and branch for my use case until this issue is resolved.  Since I don't need sanity-studio I removed all of that from my branch. I also got rid of the turbo monorepo stuff and just paired it down to the npm package.  I'm not sure that removing sanity studio was necessary but I was just poking around trying to get a better idea how everything fits together and I felt it was simpler to stick only to what I needed

Now I just point my astro project to install my fork/branch which is at
https://github.com/doesnotexist/sanity-astro/tree/astro-v4-no-sanity-studio
For my astro project I installed it like so:
```npm install  "git@github.com:doesnotexist/sanity-astro.git#astro-v4-no-sanity-studio"  --save```
With that I'm able to deploy my SSG Astro v4 site until this issue is resolved.

Maybe I should just use @sanity/client directly but I think doing that caused me some typescript issues that I don't get if I use my workaround.

**Comment by narration-sd** [comment]
For persons here, I think I've untangled what were really several problems being run into here, and on the Sanity Slack thread which is related.

I'll let you read, either on the public [Sanity Slack thread here](https://sanity-io-land.slack.com/archives/C04B7GG8YNQ/p1703016478198309?thread_ts=1701901739.752099&cid=C04B7GG8YNQ), or its text given that all shows well below..

With holiday season greetings to each, wherever you are :)

...

@Ola Christensson, perhaps I can straighten this out somewhat, having finally had a moment to look closely at what you proposed in your PR. And, other things....

There are really three things going on in this thread.

- One is due to the Astro 4 release, which your PR deals with. 

- Another I think has to do with updates on the sanity-astro plugin itself. 

- A third is that it is holiday-time, as you'll well know where you are, and on top of that, Sanity has had some very high activity in the weeks leading up to this time where everyone leaves for home.

Let's take these last-first. I think Knut, who 'owns' the sanity-astro visibility, has been very engaged. I see he commented your fix seemed to work, commented here 'merging' -- and then...not more. But if you look at the long thread in announcements for recent Sanity releases, you'll find in the last week that he had a very involving memo to write for the community. This shows definite care and therefore effort spent, and compared to it, Astro matters no doubt must wait. And now, the holidays, so wait until after.

I can add on this point that I got involved on the side of something in the Sanity development area last week also, and can tell you there was some very intense (and good) work being done there, on Presentation. So once again, other matters must take their priority turn, would seem....

Now, on the middle point, which is the one @Antonio Moton originally brought to our attention to start this thread.

I was validating your PR, and ran into the same seemingly obscure errors he showed. Looking like a Vite problem, one might look away. But observing more carefully, it's simply that there's a function Vite can't use, and it is 'sanityIntegration'.  This naming was introduced on an intermediate release of sanity-astro, and my test project as no doubt those of others was not up-to-date with it. You need in astro.config.mjs the following, to make it properly available on sanity-astro@2.1.4:
import { sanityIntegration } from '@sanity/astro'
Then, when you do that, you are very likely to get another error which looks perhaps much like the original. But this is about another change, about how you gain the sanity client. It is no longer by using this form:
```
import { useSanityClient } from "@sanity/astro";
const client = useSanityClient()
.... client.fetch(...)
```
Now, you import using the 'new' colon-form, and simply use the import wherever you need a client
``` 
import {sanityClient} from 'sanity:client';
... sanityClient.fetch(...)
```
There will be several places to change this in the examples of sanity-astro, so using global Find will let you update them all.

Now, the first point, and your PR, Ola. I had a quick look at that, under similar pressure as mentioned for others, and it didn't quite look 'right', so I looked away.

But what seemed a spelling error, it's easy with a little more time to realize is correction for an update in Astro's own spelling of the entry point -- and then your comments there also make sense.

I wondered whether having both entry points would be accepted, but I see the Vite warning about this has disappeared, so I think your PR does the job both now and for future. The primary step is of course just allowing Astro 4 in the peer dependencies.

So, Ola, I think your PR looks good from here, and sorry I can't approve it. I'm sure Knut will be back in good time to pick up his story there.

On the other problems, I think those become understood now, and hope the notes above will let anyone get their sanity-astro project into order, from whatever state they've last left it.

Last note is that I've been using Astro 4 with all sanity-astro's features quite heavily on the progress of the now-to-be-named sanity-astro-presentation project, and with no issues at all -- it 'just works'.  As we like :)

Best and in holiday spirits,
Clive

**Comment by olach** [comment]
@narration-sd Regarding your comment:

> I wondered whether having both entry points would be accepted, but I see the Vite warning about this has disappeared, so I think your PR does the job both now and for future.

If you read the upgrade guide for Astro 4, there you find everything you need to know for end users and library authors to support Astro 4:

https://docs.astro.build/en/guides/upgrade-to/v4/#renamed-entrypoint-integrations-api

> If you’re a library author who wants to support both Astro 3 and 4, you can specify both entryPoint and entrypoint, in which case, a warning will not be logged.

As a final note. Sanity is a paid product, and our clients are paying a lot of money for this service. It is a bit sad to see this "Official Sanity/Astro integration" be broken for current and new customers. Especially since there already is a fix in place, but the PR is in a limbo and not merged yet.

**Comment by narration-sd** [comment]
Well, you and @frankstallone are being kind of a tough crowd here, don't you think, @olach ?

In fact, I think you'll find there's much more behind this, if you try to use the patched item in more than a simple model's monorepo, or to deliver on a service like Netlify. This sort of thing is normal with software, and it's hit rather hard here, as large things mysteriously go missing, with few clues.

To get around the issues for the moment, you need an npm-pullable module, and I've provided that, along with some ideas where the overall fixes may lie. Notes[ center here](https://sanity-io-land.slack.com/archives/C04B7GG8YNQ/p1703128110055249?thread_ts=1703109781.623339&cid=C04B7GG8YNQ), as I know you are both on the Sanity Slack, and others need to be if participating.

As I explained before there, I was honoring your first sight on this little forest of problems, and this package uses your work, attributes it. 

It is not a prefect world, and the rest of what I said was to encourage us all to appreciate the situations and efforts of others in it. Perhaps just a little better, perhaps in this season we might...

**Comment by frankstallone** [comment]
> Well, you and @frankstallone are being kind of a tough crowd here, don't you think, @olach ?

No. 

I am being objective. You can't really hear my tone via the web so I imagine being objective can come off like tough love. 

For the last ten years of my career I have worked on heavy Node based applications. Dependency hell is real. If you are working on a feature or enhancement in six weeks, five months to merge a pull request is useless - but the world moves on. I ended up making that code my own. Problem solved. As for situations like this, again in the Enterprise world, you love to see new great things like Astro 4 come out, you get excited, but because you have dependencies, you have to wait for them all, or the marjority of them all, to upgrade before you can integrate. This ends up with apps becoming legacy codebases. Rarely are React apps on the latest version of React if there are larger breaking changes between versions. 

As for the agency side of the world, I simply want off WordPress. I have been writing PHP, and appreciated Laravel, for many years designing and developing marketing sites for customers. Long story short, after spending my time writing React, dealing with the — lovely — build systems required for nearly a decade I have finally found a winning combo with Astro and, in some cases, a headless CMS like Sanity. Any criticism I show here is because I, as a community member, want more. I want Sanity to be incredibly successful. That may look like new features and enhancements for some crowds. That looks like maintaining what exists for others. 

@narration-sd thank you for the work around. I am sure it's appreciated and will be used by some here. Personally, I'll wait to upgrade my Astro sites with Sanity to version 4.0 whenever the official `sanity-astro` plugin supports Astro 4.

**Comment by narration-sd** [comment]
> @narration-sd thank you for the work around. I am sure it's appreciated and will be used by some here. Personally, I'll wait to upgrade my Astro sites with Sanity to version 4.0 whenever the official sanity-astro plugin supports Astro 4.

Thanks, Frank, and indeed that feels a wise plan. I've run up the very latest to assure my Astro Sanity Presentation project is sound with it, but in fact for demos I'm sticking to Astro 3 code. 

The reason is just a normal one, in today's software world, that things aren't quite as solidly in place for the fresher releases. Sanity is very good with this, excellent team, but they keep making large strides, and it's necessary after to complete what they learn from early adopters. I know from contact they've been both excellent and very busy, plus it's holidays now.

I've got a 'few' decades on you, in more frames than this software one, though it seems to remain in touch, and feel you're on a wise track. I note your constant reach and learning also in the forums, and enjoy that. React in particular, least said soonest mended, right? :) but it is usable and people do, so we track it.

Hope you'll be enjoying your holidays, and best wishes for them, you and Ola both of course. This item will all wash out, and there's a note on the Slack forum from Sanity, indicating so, thus patience will win through, and for all.

Best, and a smile before our rainstorm,
Clive

**Comment by olach** [comment]
> Well, you and @frankstallone are being kind of a tough crowd here, don't you think, @olach ?

Sorry @narration-sd if that is your impression of me during these discussions. It was not my intention. My only intention has been to help the Sanity team to recognize that their official Astro integration is not working. To help them I created a functional PR. The response from the Sanity team has been since been fairly silent. And looking through the issues and PRs on this repo indicates that this Astro integration does not get the love it requires.

If Sanity had been a free open source product that was being developed in the open from individuals in their free time, I would not have expected them to fix every single issue or PR in short notice.

But Sanity is a paid product, and our clients and paying them a lot of money every months for their service. So as one of their customer, I would say that it is indeed a valid complaint to say that they are neglecting this official Astro integration. An integration that they are promoting on their website and that we are using.

If no one had raised their voice and told them that their integration was broken, how long would it take before they discovered this? Who knows how many potential new Sanity customers that has been turned away because of this broken integration? People who followed their official guide on their website, how to use Sanity for their Astro project, only to realize that it is not working. Maybe they tried another CMS instead?

So my intention was only to give awareness for this issue, not only so I can finally upgrade our own projects to Astro 4. But I was also thinking of all new Sanity users who are trying out Sanity for the first time, only to find out that the integration is broken. Not a good first impression for a paid product.

But I was reading some good news in the Slack channel that this integration maybe are going to get fixed soon. Let's hope so, for our sake, and for all new Sanity users. Until then, Merry Christmas to all!

**Comment by narration-sd** [comment]
Hi Ola, @olach, just a quick moment here to say thanks, and that reading what you say,it feels we're very much in agreement, in seeing what's desirable both for Sanity and for the community.

I'd like to suggest that the interesting thing here is the manner of approach, isn't it? 

A smile, then, as I've just cut out entirely, an early-morning essay about things you know as well as I do, about Sanity's effort level on the moment's big releases, how of course they have to proportion for this, so that some things take longer; and as centrally about what we recognize to be their unusual intent and attention to respond very well and accurately, to each thing their developers and customers tell them. 

I know we want to act in solidarity with this, and also that it's tough when the feeling might be that someone's not listening. 

I would just counsel that I think they haven't stopped listening, and may have realized also what I found, that this problem (set) we discussed is subtle and a bit more demanding than it first seemed; likely needing a reckoning with one or more third party's changes, thus its own moment of time.

You'd fill in as I would, then I suspect, that the thing is to be patient, to put in our remedies to work through the moment, and attune our language and any reiteration to supporting the players, who need it as much as any smaller one does, in the way that always seems to fall out of human efforts....

That's how my view works, anyway, and the only reason I kind of resisted a bit above.

You take care, Ola, and will wish much enjoyment, in the days that are becoming here today 🌲

Clive

**Comment by narration-sd** [comment]
A last comment here, as I've had a chance to explore where I'd found some hinted problems. Most are resolved, but there is one remaining which occurs I believe with the current @sanity/astro just upgraded with @olach Ola's fixes. 

I've explained on a reply in Sanity Slack [here](https://sanity-io-land.slack.com/archives/C04B7GG8YNQ/p1703374003802159?thread_ts=1703109781.623339&cid=C04B7GG8YNQ), and the upshot is that all looks to be well with Astro 3 or Astro 4 using Ola's contribuiton, provided you copy from the fresh repo, to put the package source itself into your monorepo, as Knut's example shows. This works locally, and also on Netlify, as I tested both, including operations with Presentation.

The present upgraded source isn't published as a package officially, and my temporary package is being taken down as is appropriate. I'm sure full Astro 4 capability will arrive in due course, and until then, you have the source inclusion method to allow working with it.

A happy holidays, then, to each; and I'm back to mine :)

**Comment by narration-sd** [comment]
Ok, unfortunately what I said just above is not quite true.

There are **_a lot_** of moving parts here, is the best answer I can come up with for why that's so, and has taken so many hours to come to enough understanding.

In a project I am able to rebuild with cleared cache on Netlify, actually the earlier published @sanity/astro works, without Ola's improvements. But, apparently Netlify doesn't check peerDependecies, at least by default.

However, this same project isn't able to build now on the laptop, though it did a week or so ago. I got it to go once this afternoon, then noticed what looked like a mistake, and removed all node_modules to assure what packages I was getting. After this, I couldn't npm install without defeating peerDependencies, our original problem on this issue.

The published @sanity/astro package had been in node_modules, before, is how it worked the first time. And when I tried to use my own fork identical to the now-official one, this failed in 'interesting' ways. I believe that's because it's build against packages that have advanced since the official deploys. Some of those many moving parts....

What I said above about simply including that source for @sanity/astro actually doesn't work, in another interesting way. I'm not describing these, because they are gross package-linking faults. The packages are present; my JetBrains dev tools believe they're nicely connected, but Vite doesn't think so. I thought this method did for a while, because of the same small own-source error I mentioned.

I think this leaves us at two points. 

- for Astro 4 work, you can use even the original @sanity/astro package off npm, provided you install it with the --legacy-peer-deps flag. Yes, this is an unclean method, but it works with my quite reasonably complicated system you know about, now giving full Sanity Presentation abilities visible in the Slack #astro movie demo this week. That's what's in that Netlify deployment just mentioned.

- Then, it's pretty clear that @sanity/astro will need some Vite/Rollup work, before it will be ready to run in Astro 4 without fixups. The result might be just one version, if those packages will get along -- we can hope for that. The release notes for Vite are pretty clear that breaking changes from 4 to 5, as Astro  4 requires, have been prevalent, particularly from Rollup underneath, so we can have empathy here....

Now I really am off for my holidays, and greet you each with a smile for yours :)
